#!/usr/bin/env python3
"""Per-card files <-> bundled scenario/events JSON.

The engine fetches one file per scenario (engine/engine.js), so the bundles
games/nebakov/scenario.json and games/nebakov/events.json stay the thing that
ships. This tool keeps a one-file-per-card copy next to them, so a change to a
single card is a single-file diff:

    games/nebakov/cards/_manifest.json          bundle metadata + card order
    games/nebakov/cards/scenes/<id>.json        one story card
    games/nebakov/cards/encounters/<id>.json    one card of deck N

Commands
    split     bundles      -> per-card files   (bundles are the input)
    build     per-card     -> bundles          (per-card files are the input)
    check     rebuild in memory and report any drift between the two
    validate  structural checks on the bundles

`split` and `build` round-trip losslessly, so whichever direction you work in,
run the other one afterwards and commit both. `check` tells you if they differ.
"""

import argparse
import json
import os
import sys
from collections import Counter, defaultdict

GAME_DIR = os.path.join("games", "nebakov")
SCENARIO = os.path.join(GAME_DIR, "scenario.json")
EVENTS = os.path.join(GAME_DIR, "events.json")
CARDS_DIR = os.path.join(GAME_DIR, "cards")
SCENES_DIR = os.path.join(CARDS_DIR, "scenes")
ENCOUNTERS_DIR = os.path.join(CARDS_DIR, "encounters")
MANIFEST = os.path.join(CARDS_DIR, "_manifest.json")

INDENT = 2


def read_json(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, indent=INDENT)
        fh.write("\n")


def dumps(data):
    return json.dumps(data, ensure_ascii=False, indent=INDENT, sort_keys=True)


# ---------------------------------------------------------------- split

def cmd_split(args):
    scenario = read_json(SCENARIO)
    events = read_json(EVENTS) if os.path.exists(EVENTS) else None

    scenes = scenario["scenes"]
    manifest = {
        "note": "Generated by tools/cards.py. Card bodies live one per file in "
                "cards/scenes and cards/encounters; this file holds the bundle "
                "metadata and the order cards are written back in.",
        "scenario": {k: v for k, v in scenario.items() if k != "scenes"},
        "sceneOrder": [s["id"] for s in scenes],
    }
    if events is not None:
        manifest["events"] = {k: v for k, v in events.items() if k != "cards"}
        manifest["encounterOrder"] = [c["id"] for c in events["cards"]]

    written = removed = 0
    for directory, cards in ((SCENES_DIR, scenes),
                             (ENCOUNTERS_DIR, events["cards"] if events else [])):
        os.makedirs(directory, exist_ok=True)
        wanted = set()
        for card in cards:
            path = os.path.join(directory, card["id"] + ".json")
            wanted.add(os.path.basename(path))
            write_json(path, card)
            written += 1
        # drop files for cards that no longer exist
        for name in os.listdir(directory):
            if name.endswith(".json") and name not in wanted:
                os.remove(os.path.join(directory, name))
                removed += 1

    write_json(MANIFEST, manifest)
    print(f"split: {written} karet zapsáno"
          + (f", {removed} osiřelých smazáno" if removed else ""))
    return 0


# ---------------------------------------------------------------- build

def load_cards(directory, order):
    if not os.path.isdir(directory):
        return []
    on_disk = {n[:-5] for n in os.listdir(directory) if n.endswith(".json")}
    missing = [i for i in order if i not in on_disk]
    if missing:
        raise SystemExit(f"chybí soubory karet v {directory}: {missing}")
    # manifest order first, then anything new on disk (so a hand-added card
    # is picked up instead of silently ignored)
    ids = list(order) + sorted(on_disk - set(order))
    cards = []
    for cid in ids:
        card = read_json(os.path.join(directory, cid + ".json"))
        if card.get("id") != cid:
            raise SystemExit(f"{cid}.json má uvnitř id={card.get('id')!r}")
        cards.append(card)
    return cards


def assemble():
    manifest = read_json(MANIFEST)
    scenario = dict(manifest["scenario"])
    scenario["scenes"] = load_cards(SCENES_DIR, manifest.get("sceneOrder", []))
    events = None
    if "events" in manifest:
        events = dict(manifest["events"])
        events["cards"] = load_cards(ENCOUNTERS_DIR,
                                     manifest.get("encounterOrder", []))
    return scenario, events


def cmd_build(args):
    scenario, events = assemble()
    errors, warnings = validate(scenario, events)
    if errors and not args.force:
        for e in errors:
            print("  chyba: " + e, file=sys.stderr)
        raise SystemExit("build zastaven (--force pro přepsání)")
    write_json(SCENARIO, scenario)
    if events is not None:
        write_json(EVENTS, events)
    print(f"build: {len(scenario['scenes'])} scén"
          + (f" + {len(events['cards'])} karet events" if events else ""))
    for e in errors:
        print("  chyba (přepsáno --force): " + e)
    for w in warnings:
        print("  varování: " + w)
    return 0


def cmd_check(args):
    built_scenario, built_events = assemble()
    drift = []
    if dumps(built_scenario) != dumps(read_json(SCENARIO)):
        drift.append(SCENARIO)
    if built_events is not None and os.path.exists(EVENTS):
        if dumps(built_events) != dumps(read_json(EVENTS)):
            drift.append(EVENTS)
    if drift:
        print("DRIFT: per-card soubory nesouhlasí s bundlem: "
              + ", ".join(drift), file=sys.stderr)
        print("       spusť `python3 tools/cards.py build` (nebo `split` "
              "podle toho, co je novější)", file=sys.stderr)
        return 1
    print("check: per-card soubory a bundle jsou shodné")
    return 0


# ---------------------------------------------------------------- validate

def validate(scenario, events=None):
    """Structural checks.

    Errors would corrupt a playthrough (a goto that leads nowhere, a cycle)
    and block `build`. Warnings describe the state of the content — an
    unfinished branch is a normal stage of authoring, not a broken file — so
    they are reported and let through.
    """
    errors, warnings = [], []
    scenes = scenario.get("scenes", [])
    by_id = {}
    for s in scenes:
        if s["id"] in by_id:
            errors.append(f"duplicitní id: {s['id']}")
        by_id[s["id"]] = s

    dup_codes = [c for c, n in Counter(
        s.get("cardCode") for s in scenes if s.get("cardCode")).items() if n > 1]
    if dup_codes:
        errors.append(f"duplicitní cardCode: {sorted(dup_codes)}")

    adj = defaultdict(list)
    # Edges a card declares as a return to somewhere already seen. B03's optional
    # minute of silence leads to B02 and B02 leads back — a loop the players walk
    # exactly once, because arriving at B02 locks the task that led there. The
    # cycle check below would otherwise report the whole rest of the game, so the
    # edge is excluded from it and kept for reachability.
    returns = defaultdict(list)
    for s in scenes:
        for c in s.get("choices") or []:
            tgt = c.get("goto")
            if not tgt:
                continue
            if tgt not in by_id:
                errors.append(f"{s['id']}: goto míří na neexistující {tgt}")
            elif c.get("revisit"):
                returns[s["id"]].append(tgt)
            else:
                adj[s["id"]].append(tgt)

    # A private card is reached by being handed to somebody, not by a goto: C11
    # is the curse the killer keeps, D12 the hint the two guards read. Without
    # this they look orphaned.
    private = defaultdict(list)
    for s_ in scenes:
        sources = (s_.get("effects") or []) + [
            e for c in (s_.get("choices") or []) for e in (c.get("effects") or [])]
        for effect in sources:
            if effect.get("type") in ("hold_card", "show_private"):
                target = effect.get("card")
                if target and target in by_id:
                    private[s_["id"]].append(target)

    reach = defaultdict(list)
    for node in set(adj) | set(returns) | set(private):
        reach[node] = adj[node] + returns[node] + private[node]

    start = scenario.get("startScene")
    if start and start not in by_id:
        errors.append(f"startScene={start} neexistuje")

    # reachability from startScene
    if start in by_id:
        seen, stack = set(), [start]
        while stack:
            n = stack.pop()
            if n in seen:
                continue
            seen.add(n)
            stack.extend(reach[n])
        unreached = sorted(set(by_id) - seen)
        if unreached:
            warnings.append(
                f"nedosažitelné ze startScene ({len(unreached)}): {unreached}")

    # cycles (Kahn)
    indeg = {i: 0 for i in by_id}
    for u in adj:
        for v in adj[u]:
            indeg[v] += 1
    queue = [i for i, d in indeg.items() if d == 0]
    i = ordered = 0
    while i < len(queue):
        u = queue[i]
        i += 1
        ordered += 1
        for v in adj[u]:
            indeg[v] -= 1
            if indeg[v] == 0:
                queue.append(v)
    if ordered != len(by_id):
        stuck = sorted(k for k, dv in indeg.items() if dv > 0)
        errors.append(f"graf obsahuje cyklus, uzly: {stuck}")

    # reputation effect vs. its toast wording
    for s in scenes:
        fx = s.get("effects") or []
        rep = next((e["value"] for e in fx if e.get("type") == "reputation"), None)
        toast = next((e.get("text", "") for e in fx if e.get("type") == "toast"), None)
        if rep is None or toast is None:
            continue
        low = toast.lower()
        if (rep > 0 and "ztrat" in low) or (rep < 0 and "získal" in low):
            warnings.append(f"{s['id']}: reputation {rep:+d} vs. toast {toast!r}")

    # declared sidecar files
    for key in ("legend", "roleSet", "events"):
        name = scenario.get(key)
        if name and not os.path.exists(os.path.join(GAME_DIR, name)):
            errors.append(f"{key}: {name} neexistuje")

    if events is not None:
        ev_ids = [c["id"] for c in events.get("cards", [])]
        clash = sorted(set(ev_ids) & set(by_id))
        if clash:
            errors.append(f"id je i ve scenes i v events: {clash}")
        top = events.get("topCard")
        if top and top not in ev_ids:
            errors.append(f"topCard={top} není v events")

    return errors, warnings


def cmd_validate(args):
    scenario = read_json(SCENARIO)
    events = read_json(EVENTS) if os.path.exists(EVENTS) else None
    errors, warnings = validate(scenario, events)
    print(f"validate: {len(scenario['scenes'])} scén"
          + (f", {len(events['cards'])} karet events" if events else "")
          + f" — {len(errors)} chyb, {len(warnings)} varování")
    for e in errors:
        print("  chyba: " + e, file=sys.stderr)
    for w in warnings:
        print("  varování: " + w)
    return 1 if errors else 0


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("split", help="bundle -> per-card soubory").set_defaults(fn=cmd_split)
    b = sub.add_parser("build", help="per-card soubory -> bundle")
    b.add_argument("--force", action="store_true",
                   help="zapsat i když validace najde chyby")
    b.set_defaults(fn=cmd_build)
    sub.add_parser("check", help="ohlásit rozdíl mezi per-card soubory a bundlem").set_defaults(fn=cmd_check)
    sub.add_parser("validate", help="strukturální kontroly bundlu").set_defaults(fn=cmd_validate)
    args = parser.parse_args()
    raise SystemExit(args.fn(args))


if __name__ == "__main__":
    main()
